### ISSUE TITLE
Require 3.1.0 can't compile sscan on newest e3

### ISSUE THREAD

**Issue by gabrielfedel** [icshwi/require-ess#15]
I think I've found a error on require 3.1.0, using the newest e3 environment. If I try to run?
bash e3.bash -c mod

I will have a problem with sscan module:

```
>> SNC is defined as /snc
/bin/bash: /snc: No such file or directory
make[4]: *** [scanProg_snl.dbd] Error 127
make[3]: *** [build] Error 2
make[2]: *** [build] Error 2
make[1]: *** [build] Error 2
make: *** [build] Error 2
build_modules all_modules main : Building Error at e3-sscan: Please check the building error: 
The command '/bin/sh -c source tools/setenv && /bin/bash e3.bash -c mod' returned a non-zero code: 1
```

I've found the error, the file App/Tools/driver.makefile set SNC from a wrong place (using E3_SITELIBS_PATH). I can fix it, but I'm not sure what is the best way to use this fix:
* make a branch, and then move tag v3.1.0 for there?
* create a patch file on e3-require ?
* other way?

If someone can advise me, I will fix this.

**Comment by jeonghanlee** [comment]
That is not related with require, that is the sequencer issue. Which base do you use? Which sequencer do you use?

**Comment by jeonghanlee** [comment]
This is completely unrelated issue, and I recommend you to upgrade require 3.1.2 instead of 3.1.0.

**Comment by jeonghanlee** [comment]
Please look at one of old travis jobs. https://travis-ci.org/icshwi/e3/jobs/567254823
It worked fine. So please provide your base version, and sscan version, and sequencer version to me.

**Comment by gabrielfedel** [comment]
I'm using base 3.15.16, sequencer 2.2.6 and sscan 1339922

**Comment by jeonghanlee** [comment]
I will check them. Maybe I am missing somethings....

**Comment by gabrielfedel** [comment]
Thank you

**Comment by jeonghanlee** [comment]
@gabrielfedel , you are right. I am wrong. SiteLib and its symbolic links were removed according to few discussion with @waynelewis. That version doesn't cover this scenario properly.

**Comment by gabrielfedel** [comment]
@jeonghanlee I can fix or help to fix. But I don't know how is the best way to do this...

**Comment by jeonghanlee** [comment]
Do you really need this version? Why not 3.1.2?

**Comment by jeonghanlee** [comment]
@gabrielfedel , in case, I readjusted the tag 3.1.0 to point the different hash id, which the correct driver.Makefile. However, you have to recompile all modules anyway. So my question is still valid, do you need 3.1.0?

**Comment by gabrielfedel** [comment]
Thank you @jeonghanlee! I will test the 3.1.2 on our systems, I think is the best solution.
